package org.tio.http.server.showcase.model;

import org.tio.http.server.showcase.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {

	private static final long serialVersionUID = 7038736722168521022L;

}
